name: tennis_booking
description: Tennis Booking App.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  bloc: ^8.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.4
  go_router: ^6.5.3
  http: ^0.13.5
  intl: ^0.18.0
  lottie: ^2.3.1
  oxidized: ^5.3.0
  shared_preferences: ^2.1.0
  shimmer: ^2.0.0
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/svg/weather/
    - assets/images/
    - assets/lotties/
    - fixtures/
